### ISSUE TITLE
QR Code Approach

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/waci-presentation-exchange#13]
The WACI spec includes a short message format for use inside a link or a QR code: https://github.com/decentralized-identity/waci-presentation-exchange/blob/main/spec/spec.md#qr-code-or-link

DIDComm V2 has a method for passing messages in a URL or a QR code: https://identity.foundation/didcomm-messaging/spec/#out-of-band-messages

This method is very universal and supports many things beyond the scope of this particular work. Note the short url message retrieval option for shorter URLs and less dense QR codes. 

If we decided to use the DIDComm defined QR codes, we should define the simplest use possible use for the narrow path we are targeting.

Thoughts? Should we choose the simplest possible DIDComm QR method, or should we stick with the method contained in the WACI original spec?

**Comment by TelegramSam** [comment]
Contents of message:

```json=
{
  "type": "https://didcomm.org/out-of-band/2.0/invitation",
  "id": "<id used for context as pthid>",
  "body": {
      "goal_code": "streamlined-vp",
      "accept": ["didcomm/v2"],
      "services": ["did:example:verifier"]
  }
}
```

Encoding details: https://identity.foundation/didcomm-messaging/spec/#standard-message-encoding

**Comment by kdenhartog** [comment]
I've been reviewing what we do in DIDCommV2 recently and would like to see us move closer to a common pattern. The other related discussion to this that I've seen that would be good to inform us is this: https://github.com/digitalbazaar/vpqr/issues/5

The common theme I'm noticing here is that we're all within the same ballpark, but we're still all slightly different. Based on that thread linked above, I think it would be useful for us to head in the direction of universal links and make it a more generalized solution for DIDComm. Right now when I read the standard message encoding it still feels like we're effectively creating bespoke solutions per transport which is a pain point to implement.

I think if we can get to a point where there we have a common way to encode any message (not just plaintext ones) into a universal link URI (and change this standard message encoding scheme to do this which is close, but not quite there yet) then it's up to the transport layer to define how that gets passed.

Then in the WACI work we just need to utilize the URI scheme from DIDCommV2 and HTTPS transport definitions here. While I suspect we'll need to keep the pickup style messaging in WACI later (same as DIDCommV2 shorted URL method), I'm leaning towards not utilizing that initially since it will be harder to extend the DIDCommV2 message from the pickup style format then it will be to go in the opposite direction. Similarly the pickup style implies architectual conflation at the transport layer because you're forced to rely on being able to pick it up which will more likely lead to bespoke designs if we ever decided to support a different transport with this protocol.

**Comment by TelegramSam** [comment]
Given the commentary in that Issue, I'm not included to go that direction at the moment. We should talk about the original intent behind the URL encoding, and see if it still applies.

**Comment by kdenhartog** [comment]
Ok, I've been discussing this internally as well. There's enough shakiness on this topic that I don't think anything that we decide is going to be "right" long term. Including the described approach around usage of `didcomm://` in the standard message engoing section. Because of that it likely makes more sense to go with the "easiest to implement solution" for v0.1 work here and then find a better long term solution which gets pushed into the DIDCommV2 work when it's more set. The universal links work seems like the "right" approach to me long term, and I think by revisit the original intent we'll uncover if it actually is or if my hunch is off.

In terms of next steps for WACI though I'm not exactly certain what "easiest to implement" actually is because easiest to implement for v0.1 I think could be different from "easiest to implement" long term if more than HTTPS gets supported.

**Comment by TelegramSam** [comment]
WG 20210607 We decided to just pick one to move fast, defaulting to the defined DIDComm encoding method to start.

**Comment by brentzundel** [comment]
WG 20210614 @TelegramSam will turn this into a PR
