### ISSUE TITLE
Spec link is broken

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/waci-presentation-exchange#78]
https://identity.foundation/waci-presentation-exchange/

**Comment by nembal** [comment]
https://identity.foundation/waci-presentation-exchange/ <- it works now @OR13

**Comment by brentzundel** [comment]
hmm, I'm still getting a 404 
![image](https://user-images.githubusercontent.com/10376511/128078890-4a4f380e-7193-4085-b142-4a27756be4f3.png)

**Comment by bumblefudge** [comment]
yup was up for a while, now back down. something glitching out in the DNS mapping, maybe, I've had that problem with GHPages in the past

**Comment by OR13** [comment]
cc @csuwildcat

**Comment by csuwildcat** [comment]
This isn't a Spec-Up issue - looks like someone moved the specs.json out of the root and completely changed the structure of the repo. Because of that, and the fact there is no longer an HTML file where the link is pointing, it is a 404. Move the specs.json to the right place and make sure that your link points to the right path you have chosen to render it to.

**Comment by csuwildcat** [comment]
I don't know what happened, but I think you may just need to put this file back at the root: https://github.com/decentralized-identity/waci-presentation-exchange/blob/main/spec/specs.json

**Comment by brentzundel** [comment]
now resolved
