### ISSUE TITLE
Establishing trust between the holder and relying party

### ISSUE THREAD

**Issue by wyc** [decentralized-identity/waci-presentation-exchange#9]
As a holder who may present credentials to a relying party, I want to have some assurances that the person receiving my credentials behind the QR code is actually the party to whom I'm intending to send my information. It would be especially convenient to have them send a presentation to me containing claims proving who they are before I send them anything of mine.

One simple approach building upon what exists may be embedding along with the nonce-like string a Verifiable Presentation to the challenge token response that has the data subject of the challenge token URL signed by a trusted party.

@kdenhartog had mentioned that DIDComm has this capability. Could you please elaborate? Thanks!

cc @csuwildcat does Credential Manifest have a space for these RP claims or could it grow to house them?

**Comment by OR13** [comment]
I think this is out of scope for v0.1, assume that the holder trusts the challenge token provider, either because they are already logged in, or they are on a web origin that is cryptographically tied to the verifier 

Recommend closing this issue, it's out of scope, or moving it to another DIF repo like PE spec or CM spec.

**Comment by wyc** [comment]
If the assumption is that the holder trusts the verifier enough to share data, then yes, I will close this.

**Comment by OR13** [comment]
@wyc I think that holds for now, yes.
